### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Joist | Contractor Estimate, Invoice, and Payments App
email: contact@sandoche.com
description: #1 App for Contractors. Estimate, invoice, collect payments, and manage projects from anywere at any time. 4.5 out of 5 avg. App Store rating. Try it Free.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.joist.com/" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: armen_mkrtchian
github_username:  armen
author: Armen Mkrtchian
logo: assets/images/large-logo.png
twitter:
  username: armen_mkrtchian
social:
  name: Armen Mkrtchian
  links:
    - https://www.linkedin.com/in/armenmkrtchian
    - https://github.com/armenm
    - https://medium.com/@armen.mkrtchian
    - https://twitter.com/armen_mkrtchian
    - https://www.facebook.com/time.party

languages: ["en"]
ampdir: amp

github: https://github.com/Armenm/Mobile-app-landingpage-template

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
